#!/bin/bash
set -e
cd "$(dirname "$0")"

CLANDRO_PKG_NAME="clandro-x11-nightly"
CLANDRO_PKG_HOMEPAGE="https://github.com/cl-andro/clandro-x11"
CLANDRO_PKG_DESCRIPTION="Companion package for clandro-x11 app"
CLANDRO_PKG_MAINTAINER="ZaidAlamgir"
CLANDRO_PKG_REVISION=0
CLANDRO_PKG_VERSION=$(grep "version =" app/build.gradle | cut -d '"' -f 2)
CLANDRO_PKG_DEPENDS="xkeyboard-config"

CLANDRO_PKG_FULLVERSION="$CLANDRO_PKG_VERSION-$CLANDRO_PKG_REVISION"

### Deploy .deb package

DEB_PACKAGE_PATH=app/build/outputs/apk/debug/${CLANDRO_PKG_NAME}-${CLANDRO_PKG_FULLVERSION}-all.deb
PACMAN_PACKAGE_PATH=app/build/outputs/apk/debug/${CLANDRO_PKG_NAME}-${CLANDRO_PKG_FULLVERSION}-any.pkg.tar.xz

INTERMEDIATES=shell-loader/build/intermediates
DATA_DIR=$INTERMEDIATES/data
CONTROL_DIR=$INTERMEDIATES/control
PACKAGE_DIR=$INTERMEDIATES/package
PREFIX=$DATA_DIR/data/data/com.zk.clandro/files/usr

rm -rf $DEB_PACKAGE_PATH $PACMAN_PACKAGE_PATH $DATA_DIR $CONTROL_DIR $PACKAGE_DIR $INTERMEDIATES/.PKGINFO $INTERMEDIATES/.BUILDINFO $INTERMEDIATES/.MTREE

mkdir -p $PREFIX/bin/
mkdir -p $PREFIX/libexec/clandro-x11
mkdir -p "$(dirname $DEB_PACKAGE_PATH)"

cp clandro-x11 $PREFIX/bin/
cp clandro-x11-preference $PREFIX/bin/
cp shell-loader/build/outputs/apk/debug/shell-loader-debug.apk \
	$PREFIX/libexec/clandro-x11/loader.apk

mkdir -p $CONTROL_DIR
cat <<EOF > $CONTROL_DIR/control
Package: $CLANDRO_PKG_NAME
Architecture: all
Maintainer: $CLANDRO_PKG_MAINTAINER
Version: $CLANDRO_PKG_FULLVERSION
Homepage: $CLANDRO_PKG_HOMEPAGE
Depends: $CLANDRO_PKG_DEPENDS
Description: $CLANDRO_PKG_DESCRIPTION
EOF

cat <<EOF > $CONTROL_DIR/postinst
#!/data/data/com.zk.clandro/files/usr/bin/sh
chmod 400 /data/data/com.zk.clandro/files/usr/libexec/clandro-x11/loader.apk
EOF

mkdir -p $PACKAGE_DIR
echo 2.0 > $PACKAGE_DIR/debian-binary
tar -cJf $PACKAGE_DIR/data.tar.xz -C $DATA_DIR .
tar -czf $PACKAGE_DIR/control.tar.gz -C $CONTROL_DIR .

ar -rsc $DEB_PACKAGE_PATH \
  $PACKAGE_DIR/debian-binary \
  $PACKAGE_DIR/control.tar.gz \
  $PACKAGE_DIR/data.tar.xz

### Deploy pacman package

BUILD_DATE=$(date +%s)
CLANDRO_PKG_INSTALLSIZE="$(du -bs $DATA_DIR | cut -f 1)"

{
  echo "pkgname = $CLANDRO_PKG_NAME"
  echo "pkgbase = $CLANDRO_PKG_NAME"
  echo "pkgver = $CLANDRO_PKG_FULLVERSION"
  echo "pkgdesc = $(echo "$CLANDRO_PKG_DESCRIPTION" | tr '\n' ' ')"
  echo "url = $CLANDRO_PKG_HOMEPAGE"
  echo "builddate = $BUILD_DATE"
  echo "packager = $CLANDRO_PKG_MAINTAINER"
  echo "size = $CLANDRO_PKG_INSTALLSIZE"
  echo "arch = any"
  echo "license = GPL-3.0"
  echo "replaces = clandro-x11"
  echo "conflict = clandro-x11"
  echo "provides = clandro-x11"
  tr ',' '\n' <<< "$CLANDRO_PKG_DEPENDS" | sed 's|(||g; s|)||g; s| ||g; s|>>|>|g; s|<<|<|g' | awk '{ printf "depend = " $1; if ( ($1 ~ /</ || $1 ~ />/ || $1 ~ /=/) && $1 !~ /-/ ) printf "-0"; printf "\n" }' | sed 's/|.*//'
} > $DATA_DIR/.PKGINFO

{
  echo "format = 2"
  echo "pkgname = $CLANDRO_PKG_NAME"
  echo "pkgbase = $CLANDRO_PKG_NAME"
  echo "pkgver = $CLANDRO_PKG_FULLVERSION"
  echo "pkgarch = any"
  echo "packager = $CLANDRO_PKG_MAINTAINER"
  echo "builddate = $BUILD_DATE"
} > $DATA_DIR/.BUILDINFO

{
  echo "post_install() {"
  echo "    chmod 400 /data/data/com.zk.clandro/files/usr/libexec/clandro-x11/loader.apk"
  echo "}"
  echo "post_upgrade() {"
  echo "    post_install"
  echo "}"
} > $DATA_DIR/.INSTALL

PACMAN_PACKAGE_PATH=`realpath $PACMAN_PACKAGE_PATH`

cd $DATA_DIR
shopt -s dotglob globstar
mapfile -d '' FILES < <(printf '%s\0' .BUILDINFO .INSTALL .PKGINFO data/**/*)
shopt -u dotglob globstar

# Bsdtar is missing in Github CI image and installing it takes a while
# so effectively this code replaces
# printf '%s\0' data/**/* .BUILDINFO .INSTALL .PKGINFO | bsdtar -cnf - --format=mtree --options='!all,use-set,type,uid,gid,mode,time,size,md5,sha256,link' --null --files-from - | gzip -c -f -n > .MTREE
# printf '%s\0' data/**/* .BUILDINFO .INSTALL .PKGINFO .MTREE | bsdtar --no-fflags -cnf - --null --files-from - | xz > "$PACMAN_PACKAGE_PATH"

{
_mode="664"
echo "#mtree"
echo "/set type=file uid=1000 gid=1000 mode=$_mode"
for path in "${FILES[@]}"; do
  # Skip non-existing paths (due to globs resolving to themselves)
  [ -e "$path" ] || continue

  if [ -d "$path" ]; then
    mode="$(stat -c '%a' "$path")"
    mtime="$(stat -c '%Y' "$path").$(stat -c '%y' "$path" | cut -d'.' -f2 | cut -d' ' -f1)"
    if [ "$mode" != "$_mode" ]; then
        echo "/set mode=$mode"
        _mode="$mode"
    fi
    printf '%q time=%s type=dir\n' "$path" "$mtime"

  elif [ -f "$path" ]; then
    mode="$(stat -c '%a' "$path")"
    mtime="$(stat -c '%Y' "$path").$(stat -c '%y' "$path" | cut -d'.' -f2 | cut -d' ' -f1)"
    size="$(stat -c '%s' "$path")"
    md5="$(md5sum "$path" | cut -d' ' -f1)"
    sha256="$(sha256sum "$path" | cut -d' ' -f1)"
    printf '%q time=%s%s size=%s md5digest=%s sha256digest=%s%s\n' \
      "$path" "$mtime" "$([ "$mode" != "$_mode" ] && echo " mode=$mode")" "$size" "$md5" "$sha256"
  fi
done
} | gzip > .MTREE

printf '%s\0' "${FILES[@]}" ".MTREE" | tar --null --no-recursion --hard-dereference --files-from=- -cf - | xz > "$PACMAN_PACKAGE_PATH"
